spring:
  security:
    oauth2:
      client:
        registration:
          users-service-registration:
            provider: users-provider
            client-id: users-projeto-final
            client-secret: XA4SCAaXjCCcxMgiGgwvXTdFt6xhkYtO
            authorization-grant-type: client_credentials
        provider:
          users-provider:
            issuer-uri: http://localhost:8082/realms/digitalhouse

